default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: horse_report_development

test:
  <<: *default
  database: horse_report_test

production:
  <<: *default
